apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: exhort-integration-tests
spec:
  params:
    - description: 'Snapshot Json data'
      name: SNAPSHOT
      type: string
      default: ''
    - description: 'Application namespace'
      name: NAMESPACE
      type: string
      default: ''
  results:
    - name: JAVA_COMMUNITY_DEPENDENCIES
      value: $(tasks.maven-run.results.JAVA_COMMUNITY_DEPENDENCIES)
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.SNAPSHOT.source.git.url)"
        - name: revision
          value: "$(params.SNAPSHOT.source.git.revision)"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: MAVEN_IMAGE
          value: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-20
        - name: MAVEN_MIRROR_URL
          value: http://jvm-build-workspace-artifact-cache.$(context.taskRun.namespace).svc.cluster.local
        - name: CONTEXT_DIR
          value: "."
        - name: GOALS
          value:
            - clean
            - verify
            - -Pnative
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace