apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: exhort-integration-tests
spec:
  params:
    - description: 'Git Repository URL to clone'
      name: git-url
      type: string
      default: '{{repo_url}}'
    - description: 'Revision'
      name: revision
      type: string
      default: '{{revision}}'
    - description: 'The context directory within the repository for sources on which we want to execute maven goals. (Default: ".")'
      name: path-context
      default: '.'
      type: string
  results:
    - name: JAVA_COMMUNITY_DEPENDENCIES
      value: $(tasks.maven-run.results.JAVA_COMMUNITY_DEPENDENCIES)
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.revision)"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: MAVEN_IMAGE
          value: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-20
        - name: MAVEN_MIRROR_URL
          value: http://jvm-build-workspace-artifact-cache.$(context.taskRun.namespace).svc.cluster.local
        - name: CONTEXT_DIR
          value: "$(params.path-context)"
        - name: GOALS
          value:
            - clean
            - verify
            - -Pnative
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace